INSERT INTO USERS (USER_NAME, EMAIL) VALUES ('БОНДАРЕВ МАКСИМ', 'MOHNATISHMEL@GMAIL.COM');
INSERT INTO AUTHENTICATES (ID, LOGIN, PASSWORD) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'БОНДАРЕВ_МАКСИМ', '1');

INSERT INTO USERS (ID, USER_NAME, EMAIL) VALUES (USER_ID_SEQ_GEN.NEXTVAL, 'КАКОРА АЛЕКСЕЙ', 'AKAKORA@YANDEX.BY');
INSERT INTO AUTHENTICATES (ID, LOGIN, PASSWORD) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'КАКОРА_АЛЕКСЕЙ', '1');

INSERT INTO USERS (ID, USER_NAME, EMAIL) VALUES (USER_ID_SEQ_GEN.NEXTVAL, 'ДМИТРИЕВ АНДРЕЙ', 'MOHNATISHMEL@GMAIL.COM');
INSERT INTO AUTHENTICATES (ID, LOGIN, PASSWORD) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'ДМИТРИЕВ_АНДРЕЙ', '1');

INSERT INTO USERS (ID, USER_NAME, EMAIL) VALUES (USER_ID_SEQ_GEN.NEXTVAL, 'МАЕВСКИЙ МАКСИМ', 'KANTASENADAS@GMAIL.COM');
INSERT INTO AUTHENTICATES (ID, LOGIN, PASSWORD) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'МАЕВСКИЙ_МАКСИМ', '1');

INSERT INTO USERS (ID, USER_NAME, EMAIL) VALUES (USER_ID_SEQ_GEN.NEXTVAL, 'МАЕВСКИЙ СЕРГЕЙ', 'ROSTPROMINVEST@MAIL.RU');
INSERT INTO AUTHENTICATES (ID, LOGIN, PASSWORD) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'МАЕВСКИЙ_СЕРГЕЙ', '1');

INSERT INTO USERS (ID, USER_NAME, EMAIL) VALUES (USER_ID_SEQ_GEN.NEXTVAL, 'НЕСТЕРКОВ АЛЬГЕРД', 'S1MPLE@TUT.BY');
INSERT INTO AUTHENTICATES (ID, LOGIN, PASSWORD) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'НЕСТЕРКОВ_АЛЬГЕРД', '1');

INSERT INTO USERS (ID, USER_NAME, EMAIL) VALUES (USER_ID_SEQ_GEN.NEXTVAL, 'НОВИК ИВАН', 'NOYVIKIVAN@MAIL.RU');
INSERT INTO AUTHENTICATES (ID, LOGIN, PASSWORD) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'НОВИК_ИВАН', '1');

INSERT INTO USERS (ID, USER_NAME, EMAIL) VALUES (USER_ID_SEQ_GEN.NEXTVAL, 'ХОДОРЕНКО ЕЛЕНА', 'ALENAGOA0503@GMAIL.COM');
INSERT INTO AUTHENTICATES (ID, LOGIN, PASSWORD) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'ХОДОРЕНКО_ЕЛЕНА', '1');

INSERT INTO USERS (ID, USER_NAME, EMAIL) VALUES (USER_ID_SEQ_GEN.NEXTVAL, 'ЗАЙЦЕВ АНДРЕЙ', 'ZORGE.ABC@GMAIL.COM');
INSERT INTO AUTHENTICATES (ID, LOGIN, PASSWORD) VALUES (USER_ID_SEQ_GEN.CURRVAL, 'ЗАЙЦЕВ_АНДРЕЙ', '1');




INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (1, 1);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (1, 2);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (1, 3);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (1, 4);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (1, 5);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (1, 6);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (1, 7);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (1, 8);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (1, 9);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (2, 1);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (2, 2);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (3, 3);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (3, 4);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (3, 5);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (3, 6);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (4, 7);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (4, 8);
INSERT INTO ROLE_USER (ROLE_ID, USER_ID) VALUES (4, 9);

